### ISSUE TITLE
Document working vs WIP features

### ISSUE THREAD

**Issue by ghost** [SciML/DiffEqOperators.jl#242]
The current documentation can be misleading regarding which features are ready vs in-progress. I'm not sure if there's a standard practice for this, but if we can summarize the current state in this issue I'll update the README.

Relatedly, we might consider adding a header to the README that warns users that this library is still a WIP, and not to depend on it for anything critical. Again, not sure if there's already a standard practice for that.

So far, I'm aware that the following are broken / not implemented:

 - `UpwindDifference`
 - generally anything for 3+ dimentions

Let's make that list complete and specific.

This will hopefully avoid surprising users, as well as reduce the flow of "yes, we know" issue submissions.

**Comment by ChrisRackauckas** [comment]
I think this is just too broad to be useful. We should open issues on every specific thing that we run into, and of course there will always be uncertainty somewhere, but this is too broad. This is definitely not a core SciML library yet, which is why we don't directly advertise it anywhere, but the basics should be working according to the tests. But yes, there are edges we need to soften.

>UpwindDifference

I think it needs to be more specific. There's tests on things like its action, turning into an array, etc. so most things should be working. Here's an entire set of tests covering what we thought was everything (https://github.com/SciML/DiffEqOperators.jl/blob/73044151e6ba55f3348e0f5b59e8bea91f865923/test/upwind_operators_interface.jl), but it looks like we missed something. Banded concretization seems to be a specific issue covered in https://github.com/SciML/DiffEqOperators.jl/issues/240 . Is there anything else? 

In fact, that set of tests covers banded concretizations, so something peculiar is going on with the example or the test is faulty.

>generally anything for 3+ dimensions

Here's 1000 lines of tests on 3 dimensional actions: https://github.com/SciML/DiffEqOperators.jl/blob/73044151e6ba55f3348e0f5b59e8bea91f865923/test/2D_3D_fast_multiplication.jl#L722-L1647 . Regular grids seem fine. Irregular grids have some remaining issues. 3D BCs are 🤷 though.
